// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Read directly from process.env (not Prisma's `env()` helper, which throws
    // when the var is absent). `prisma generate` doesn't need a URL, so the
    // build must not fail when DATABASE_URL isn't set; migrate/db push still
    // pick it up at runtime when it is. Falls back to the Vercel Prisma Postgres
    // var names (POSTGRES_URL / PRISMA_DATABASE_URL).
    url:
      process.env.DATABASE_URL ||
      process.env.POSTGRES_URL ||
      process.env.PRISMA_DATABASE_URL,
  },
});
